services:
  clickhouse:
    init: true
    image: clickhouse/clickhouse-server:26.3-alpine
    ports:
      - "8123:8123"
    volumes:
      - ./server/data/clickhouse:/var/lib/clickhouse
      - ./server/etc/clickhouse/config.xml:/etc/clickhouse-server/config.d/custom.xml:ro
      - ./server/etc/clickhouse/users.xml:/etc/clickhouse-server/users.d/custom.xml:ro
      - ./server/etc/clickhouse/init:/docker-entrypoint-initdb.d:ro
    environment:
      - CLICKHOUSE_DB=hn_ngram
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
