set positional-arguments

ingest *args="download":
  cargo run -p ingest -- "$@"

ingest-dev:
  cargo run -p ingest -- process --config ingest.dev.toml "$@"

ingest-test:
  cargo run -p ingest -- process --config ingest.test.toml "$@"

import *args="":
  cargo run -p ingest -- import "$@"

up:
  watchexec -r -w crates -- cargo run -p api --bin api

test:
  cargo test

openapi:
  cargo run -p api --bin generate_openapi > openapi.json

reset-db:
  cargo run -p ingest -- reset-db

reset:
  cargo run -p ingest -- reset
